services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../:/app:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
